CREATE OR REPLACE PROCEDURE OTIF_GUARDIAN.AUDIT.SP_RUN_DQ_CHECKS()
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python')
HANDLER = 'run_dq_checks'
COMMENT = 'Production DQ framework: 12 categories, 50+ checks. CRITICAL failures block scoring.'
EXECUTE AS CALLER
AS
$$
from datetime import datetime

def run_dq_checks(session) -> dict:
    start = datetime.now()
    run_id = 'DQ_' + start.strftime('%Y%m%d_%H%M%S')
    checks = []
    seq = 0

    def add(name, cat, ds, sev, sql):
        nonlocal seq
        seq += 1
        try:
            r = session.sql(sql).collect()[0]
            actual, expected = str(r[0]), str(r[1])
            status = 'PASS' if str(r[2]).upper() in ('TRUE','1') else 'FAIL'
            err = r[3] if len(r) > 3 and r[3] else None
        except Exception as e:
            actual, expected, status, err = 'ERROR', 'N/A', 'FAIL', str(e)[:500]
        checks.append((seq, run_id, name, cat, ds, sev, status, expected, actual, err))

    # CAT 1: SCHEMA VALIDATION
    for s in ['RAW','STAGING','ANALYTICS','ML','SEMANTIC','AGENTS','STREAMLIT','AUDIT']:
        add(f'SCHEMA_{s}','SCHEMA_VALIDATION','DATABASE','CRITICAL',
            f"SELECT CASE WHEN COUNT(*)>0 THEN 'Y' ELSE 'N' END,'EXISTS',COUNT(*)>0 FROM OTIF_GUARDIAN.INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='{s}'")

    # CAT 2: REQUIRED COLUMNS
    rc = {'PO_LINES':['PO_LINE_ID','PO_ID','MATERIAL_ID','QUANTITY_ORDERED','UNIT_PRICE','LINE_STATUS','PROMISED_DELIVERY_DATE'],
          'SUPPLIERS':['SUPPLIER_ID','SUPPLIER_CODE','SUPPLIER_NAME','SUPPLIER_TIER','STATUS','HISTORICAL_OTD_PCT'],
          'PURCHASE_ORDERS':['PO_ID','SUPPLIER_ID','PLANT_ID','ORDER_DATE','PO_STATUS'],
          'MATERIALS':['MATERIAL_ID','MATERIAL_CODE','ABC_CLASS','CRITICALITY'],
          'PLANTS':['PLANT_ID','PLANT_CODE','REGION','COUNTRY_CODE','STATUS']}
    for t, cols in rc.items():
        for c in cols:
            add(f'COL_{t}_{c}','REQUIRED_COLUMNS',f'RAW.{t}','CRITICAL',
                f"SELECT CASE WHEN COUNT(*)>0 THEN 'Y' ELSE 'N' END,'EXISTS',COUNT(*)>0 FROM OTIF_GUARDIAN.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='RAW' AND TABLE_NAME='{t}' AND COLUMN_NAME='{c}'")

    # CAT 3: NULL THRESHOLDS
    for t,c,th,sv in [('PO_LINES','PO_LINE_ID',0,'CRITICAL'),('PO_LINES','QUANTITY_ORDERED',0,'CRITICAL'),
        ('PO_LINES','UNIT_PRICE',0,'CRITICAL'),('PO_LINES','PO_ID',0,'CRITICAL'),
        ('PO_LINES','PROMISED_DELIVERY_DATE',5,'WARNING'),('SUPPLIERS','SUPPLIER_ID',0,'CRITICAL'),
        ('MATERIALS','MATERIAL_ID',0,'CRITICAL'),('PURCHASE_ORDERS','PO_ID',0,'CRITICAL'),
        ('PURCHASE_ORDERS','SUPPLIER_ID',0,'CRITICAL'),('PLANTS','PLANT_ID',0,'CRITICAL')]:
        add(f'NULL_{t}_{c}','NULL_THRESHOLDS',f'RAW.{t}',sv,
            f"SELECT ROUND(COUNT_IF({c} IS NULL)*100.0/NULLIF(COUNT(*),0),2),'{th}%',COUNT_IF({c} IS NULL)*100.0/NULLIF(COUNT(*),0)<={th} FROM OTIF_GUARDIAN.RAW.{t}")

    # CAT 4: DUPLICATE DETECTION
    for t,pk in [('PO_LINES','PO_LINE_ID'),('SUPPLIERS','SUPPLIER_ID'),('PURCHASE_ORDERS','PO_ID'),('MATERIALS','MATERIAL_ID'),('PLANTS','PLANT_ID')]:
        add(f'DUP_{t}','DUPLICATE_DETECTION',f'RAW.{t}','CRITICAL',
            f"SELECT COUNT(*)-COUNT(DISTINCT {pk}),'0',COUNT(*)=COUNT(DISTINCT {pk}) FROM OTIF_GUARDIAN.RAW.{t}")

    # CAT 5: REFERENTIAL INTEGRITY (core scoring path = CRITICAL, ancillary = WARNING)
    for ch,cc,pa,pc,sv in [('PO_LINES','PO_ID','PURCHASE_ORDERS','PO_ID','CRITICAL'),('PO_LINES','MATERIAL_ID','MATERIALS','MATERIAL_ID','CRITICAL'),
        ('PURCHASE_ORDERS','SUPPLIER_ID','SUPPLIERS','SUPPLIER_ID','CRITICAL'),('PURCHASE_ORDERS','PLANT_ID','PLANTS','PLANT_ID','CRITICAL'),
        ('INVENTORY','MATERIAL_ID','MATERIALS','MATERIAL_ID','CRITICAL'),('INVENTORY','PLANT_ID','PLANTS','PLANT_ID','CRITICAL'),
        ('CUSTOMER_ORDERS','PLANT_ID','PLANTS','PLANT_ID','WARNING')]:
        add(f'FK_{ch}_TO_{pa}','REFERENTIAL_INTEGRITY',f'RAW.{ch}',sv,
            f"SELECT COUNT(*),'0',COUNT(*)=0 FROM OTIF_GUARDIAN.RAW.{ch} c LEFT JOIN OTIF_GUARDIAN.RAW.{pa} p ON c.{cc}=p.{pc} WHERE p.{pc} IS NULL")

    # CAT 6: INVALID DATES
    add('DATE_ORDER_RANGE','INVALID_DATES','RAW.PURCHASE_ORDERS','WARNING',
        "SELECT COUNT_IF(ORDER_DATE<'2024-01-01' OR ORDER_DATE>'2027-12-31'),'0',COUNT_IF(ORDER_DATE<'2024-01-01' OR ORDER_DATE>'2027-12-31')=0 FROM OTIF_GUARDIAN.RAW.PURCHASE_ORDERS")
    add('DATE_PROMISED_LT_ORDER','INVALID_DATES','RAW.PO_LINES','CRITICAL',
        "SELECT COUNT(*),'0',COUNT(*)=0 FROM OTIF_GUARDIAN.RAW.PO_LINES pl JOIN OTIF_GUARDIAN.RAW.PURCHASE_ORDERS po ON pl.PO_ID=po.PO_ID WHERE pl.PROMISED_DELIVERY_DATE IS NOT NULL AND pl.PROMISED_DELIVERY_DATE<po.ORDER_DATE")
    add('DATE_ACTUAL_LT_ORDER','INVALID_DATES','RAW.PO_LINES','WARNING',
        "SELECT COUNT(*),'0',COUNT(*)=0 FROM OTIF_GUARDIAN.RAW.PO_LINES pl JOIN OTIF_GUARDIAN.RAW.PURCHASE_ORDERS po ON pl.PO_ID=po.PO_ID WHERE pl.ACTUAL_DELIVERY_DATE IS NOT NULL AND pl.ACTUAL_DELIVERY_DATE<po.ORDER_DATE")

    # CAT 7: INVALID QUANTITIES/COSTS
    add('QTY_POSITIVE','INVALID_QUANTITIES','RAW.PO_LINES','CRITICAL',
        "SELECT COUNT_IF(QUANTITY_ORDERED<=0),'0',COUNT_IF(QUANTITY_ORDERED<=0)=0 FROM OTIF_GUARDIAN.RAW.PO_LINES")
    add('PRICE_NOT_NEGATIVE','INVALID_QUANTITIES','RAW.PO_LINES','CRITICAL',
        "SELECT COUNT_IF(UNIT_PRICE<0),'0',COUNT_IF(UNIT_PRICE<0)=0 FROM OTIF_GUARDIAN.RAW.PO_LINES")
    add('OTD_RANGE','INVALID_QUANTITIES','RAW.SUPPLIERS','WARNING',
        "SELECT COUNT_IF(HISTORICAL_OTD_PCT<0 OR HISTORICAL_OTD_PCT>100),'0',COUNT_IF(HISTORICAL_OTD_PCT<0 OR HISTORICAL_OTD_PCT>100)=0 FROM OTIF_GUARDIAN.RAW.SUPPLIERS")
    add('INV_NOT_NEGATIVE','INVALID_QUANTITIES','RAW.INVENTORY','WARNING',
        "SELECT COUNT_IF(QTY_ON_HAND<0),'0',COUNT_IF(QTY_ON_HAND<0)=0 FROM OTIF_GUARDIAN.RAW.INVENTORY")

    # CAT 8: PO/PO-LINE CONSISTENCY
    add('PO_HAS_LINES','PO_CONSISTENCY','RAW.PURCHASE_ORDERS','WARNING',
        "SELECT COUNT(*),'0',COUNT(*)=0 FROM OTIF_GUARDIAN.RAW.PURCHASE_ORDERS po LEFT JOIN OTIF_GUARDIAN.RAW.PO_LINES pl ON po.PO_ID=pl.PO_ID WHERE pl.PO_ID IS NULL")
    add('CLOSED_HAS_DATE','PO_CONSISTENCY','RAW.PO_LINES','WARNING',
        "SELECT COUNT_IF(LINE_STATUS IN ('CLOSED','SHORT_CLOSED') AND ACTUAL_DELIVERY_DATE IS NULL),'0',COUNT_IF(LINE_STATUS IN ('CLOSED','SHORT_CLOSED') AND ACTUAL_DELIVERY_DATE IS NULL)=0 FROM OTIF_GUARDIAN.RAW.PO_LINES")
    add('VALID_STATUS','PO_CONSISTENCY','RAW.PO_LINES','WARNING',
        "SELECT COUNT_IF(LINE_STATUS NOT IN ('OPEN','CLOSED','SHORT_CLOSED','CANCELLED','IN_TRANSIT','PARTIALLY_RECEIVED')),'0',COUNT_IF(LINE_STATUS NOT IN ('OPEN','CLOSED','SHORT_CLOSED','CANCELLED','IN_TRANSIT','PARTIALLY_RECEIVED'))=0 FROM OTIF_GUARDIAN.RAW.PO_LINES")

    # CAT 9: RELATIONSHIP VALIDATION
    add('SUPPLIER_STATUS','RELATIONSHIP_VALIDATION','RAW.SUPPLIERS','WARNING',
        "SELECT COUNT_IF(STATUS NOT IN ('ACTIVE','PROBATION','INACTIVE','SUSPENDED')),'0',COUNT_IF(STATUS NOT IN ('ACTIVE','PROBATION','INACTIVE','SUSPENDED'))=0 FROM OTIF_GUARDIAN.RAW.SUPPLIERS")
    add('SUPPLIER_TIER','RELATIONSHIP_VALIDATION','RAW.SUPPLIERS','WARNING',
        "SELECT COUNT_IF(SUPPLIER_TIER NOT IN (1,2,3)),'0',COUNT_IF(SUPPLIER_TIER NOT IN (1,2,3))=0 FROM OTIF_GUARDIAN.RAW.SUPPLIERS")
    add('PLANT_STATUS','RELATIONSHIP_VALIDATION','RAW.PLANTS','WARNING',
        "SELECT COUNT_IF(STATUS NOT IN ('ACTIVE','INACTIVE','MAINTENANCE')),'0',COUNT_IF(STATUS NOT IN ('ACTIVE','INACTIVE','MAINTENANCE'))=0 FROM OTIF_GUARDIAN.RAW.PLANTS")
    add('ALT_SUP_MATERIALS','RELATIONSHIP_VALIDATION','RAW.ALTERNATE_SUPPLIERS','CRITICAL',
        "SELECT COUNT(*),'0',COUNT(*)=0 FROM OTIF_GUARDIAN.RAW.ALTERNATE_SUPPLIERS a LEFT JOIN OTIF_GUARDIAN.RAW.MATERIALS m ON a.MATERIAL_ID=m.MATERIAL_ID WHERE m.MATERIAL_ID IS NULL")

    # CAT 10: ROW-COUNT ANOMALIES
    for t,lo,hi,sv in [('SUPPLIERS',10,500,'WARNING'),('PLANTS',1,100,'WARNING'),('MATERIALS',50,5000,'WARNING'),('PO_LINES',10000,999999,'CRITICAL')]:
        add(f'ROWS_{t}','ROW_COUNT_ANOMALY',f'RAW.{t}',sv,
            f"SELECT COUNT(*),'{lo}-{hi}',COUNT(*) BETWEEN {lo} AND {hi} FROM OTIF_GUARDIAN.RAW.{t}")
    add('ROWS_SCORED','ROW_COUNT_ANOMALY','ML.SCORED_PO_LINES','CRITICAL',
        "SELECT COUNT(*),'>0',COUNT(*)>0 FROM OTIF_GUARDIAN.ML.SCORED_PO_LINES")
    add('ROWS_TRAIN','ROW_COUNT_ANOMALY','ML.TRAIN_DATA_V2','CRITICAL',
        "SELECT COUNT(*),'>10000',COUNT(*)>10000 FROM OTIF_GUARDIAN.ML.TRAIN_DATA_V2")

    # CAT 11: DATA FRESHNESS
    add('FRESH_PO_LINES','DATA_FRESHNESS','RAW.PO_LINES','WARNING',
        "SELECT ROUND(DATEDIFF('hour',MAX(CREATED_AT),CURRENT_TIMESTAMP()),1),'<=168h',DATEDIFF('hour',MAX(CREATED_AT),CURRENT_TIMESTAMP())<=168 FROM OTIF_GUARDIAN.RAW.PO_LINES")
    add('FRESH_SCORING','DATA_FRESHNESS','AUDIT.SCORING_LOG','WARNING',
        "SELECT ROUND(DATEDIFF('hour',MAX(SCORED_AT),CURRENT_TIMESTAMP()),1),'<=48h',DATEDIFF('hour',MAX(SCORED_AT),CURRENT_TIMESTAMP())<=48 FROM OTIF_GUARDIAN.AUDIT.SCORING_LOG")

    # CAT 12: DISTRIBUTION CHANGES
    add('DIST_BREACH_RATE','DISTRIBUTION_CHANGE','ML.TRAIN_DATA_V2','WARNING',
        "SELECT ROUND(AVG(CASE WHEN OTIF_BREACH=1 THEN 1.0 ELSE 0.0 END)*100,2),'5-20%',AVG(CASE WHEN OTIF_BREACH=1 THEN 1.0 ELSE 0.0 END)*100 BETWEEN 5 AND 20 FROM OTIF_GUARDIAN.ML.TRAIN_DATA_V2")
    add('DIST_MEAN_PROB','DISTRIBUTION_CHANGE','ML.SCORED_PO_LINES','WARNING',
        'SELECT ROUND(AVG(prediction_result:"probability":"1"::FLOAT)*100,2),\'5-50%\',AVG(prediction_result:"probability":"1"::FLOAT)*100 BETWEEN 5 AND 50 FROM OTIF_GUARDIAN.ML.SCORED_PO_LINES')

    # ══════ WRITE RESULTS ══════
    for c in checks:
        ev = str(c[7]).replace("'","''") if c[7] else ''
        av = str(c[8]).replace("'","''") if c[8] else ''
        em = "'" + str(c[9]).replace("'","''") + "'" if c[9] else 'NULL'
        session.sql(f"INSERT INTO OTIF_GUARDIAN.AUDIT.DQ_CHECK_RESULTS(CHECK_ID,RUN_ID,CHECK_NAME,CATEGORY,DATASET,SEVERITY,STATUS,EXPECTED_VALUE,ACTUAL_VALUE,ERROR_MESSAGE,EXECUTION_TIME) SELECT {c[0]},'{c[1]}','{c[2]}','{c[3]}','{c[4]}','{c[5]}','{c[6]}','{ev}','{av}',{em},CURRENT_TIMESTAMP()").collect()

    p = sum(1 for c in checks if c[6]=='PASS')
    w = sum(1 for c in checks if c[6]=='FAIL' and c[5]=='WARNING')
    cr = sum(1 for c in checks if c[6]=='FAIL' and c[5]=='CRITICAL')
    g = 'BLOCKED' if cr > 0 else 'PASS'

    session.sql(f"INSERT INTO OTIF_GUARDIAN.AUDIT.DQ_RUN_SUMMARY VALUES('{run_id}','{start.strftime('%Y-%m-%d %H:%M:%S')}',CURRENT_TIMESTAMP(),{seq},{p},{w},{cr},'{g}')").collect()

    return {'run_id':run_id,'total_checks':seq,'passed':p,'warnings':w,'critical_failures':cr,'gate_status':g,'categories':12}
$$
